services:
  blog:
    image: postgres:18-alpine
    container_name: blog
    restart: always
    environment:
      POSTGRES_USER: blog
      POSTGRES_PASSWORD: dong2270
      POSTGRES_DB: blog
    ports:
      - 5433:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: {}
